# This is a basic workflow to help you get started with Actions

name: update gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: main
          ref: main
      - uses: actions/checkout@v2
        with:
          path: pages
          ref: gh-pages
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - name: Build `main` branch
        run: |
          cd main
          npm ci
          npm run build
          cd ..
      
      - name: Copy built `main` to `gh-pages`
        run: |
          cp main/dist/* pages/libraries
          cd pages
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: .
          clean: true
